-- =============================================================================
-- Ubukwe Rwanda Wedding Plan Management System
-- Database Initial Schema Migration (Flyway V1)
-- Target RDBMS: PostgreSQL 15+ / H2 Compatible
-- =============================================================================

-- 1. USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30),
    role VARCHAR(40) NOT NULL DEFAULT 'ROLE_BRIDE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- 2. WEDDINGS TABLE
CREATE TABLE weddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    target_budget DECIMAL(14,2) DEFAULT 0.00,
    bride_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    groom_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    partner_code VARCHAR(50) UNIQUE,
    family_code VARCHAR(50) UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_weddings_bride ON weddings(bride_id);
CREATE INDEX idx_weddings_groom ON weddings(groom_id);
CREATE INDEX idx_weddings_partner_code ON weddings(partner_code);

-- 3. WEDDING MEMBERS TABLE
CREATE TABLE wedding_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(40) NOT NULL,
    side VARCHAR(30) NOT NULL, -- BRIDE_SIDE, GROOM_SIDE, SHARED
    version BIGINT NOT NULL DEFAULT 0,
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wedding_user UNIQUE (wedding_id, user_id)
);

CREATE INDEX idx_wm_wedding_side ON wedding_members(wedding_id, side);

-- 4. WEDDING CEREMONIES TABLE
CREATE TABLE wedding_ceremonies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    ceremony_type VARCHAR(40) NOT NULL, -- TRADITIONAL (Gusaba), CIVIL, RELIGIOUS, RECEPTION, GENERAL
    ceremony_date DATE,
    start_time TIME WITHOUT TIME ZONE,
    venue_location VARCHAR(255),
    description TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ceremonies_wedding ON wedding_ceremonies(wedding_id);
CREATE INDEX idx_ceremonies_date ON wedding_ceremonies(ceremony_date);

-- 5. PLANNING CATEGORIES TABLE
CREATE TABLE planning_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT REFERENCES weddings(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    description TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_categories_wedding ON planning_categories(wedding_id);

-- 6. TASKS TABLE (Ceremony & General Tasks with Soft Delete & Side Isolation)
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    ceremony_id BIGINT REFERENCES wedding_ceremonies(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES planning_categories(id) ON DELETE SET NULL,
    assigned_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', -- LOW, MEDIUM, HIGH
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',    -- PENDING, IN_PROGRESS, COMPLETED
    visibility_scope VARCHAR(30) NOT NULL DEFAULT 'SHARED', -- BRIDE_PRIVATE, GROOM_PRIVATE, SHARED
    due_date DATE,
    estimated_budget DECIMAL(14,2) DEFAULT 0.00,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE -- Soft delete column
);

CREATE INDEX idx_tasks_wedding_visibility ON tasks(wedding_id, visibility_scope);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_deleted ON tasks(deleted_at);

-- 7. HOME PREPARATION ITEMS TABLE
CREATE TABLE home_preparations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL, -- APPLIANCES, FURNITURE, KITCHENWARE, BEDDING, RENT_UTILITIES
    item_name VARCHAR(200) NOT NULL,
    side VARCHAR(30) NOT NULL,     -- BRIDE_SIDE, GROOM_SIDE, SHARED
    assigned_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    budget_rwf DECIMAL(14,2) DEFAULT 0.00,
    due_date DATE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_home_prep_wedding_side ON home_preparations(wedding_id, side);

-- 8. BUDGETS TABLE
CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL UNIQUE REFERENCES weddings(id) ON DELETE CASCADE,
    total_planned_rwf DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. BUDGET CATEGORIES TABLE
CREATE TABLE budget_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    allocated_amount_rwf DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    visibility_scope VARCHAR(30) NOT NULL DEFAULT 'SHARED'
);

-- 10. EXPENSES TABLE (With Soft Delete & Side Privacy)
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    ceremony_id BIGINT REFERENCES wedding_ceremonies(id) ON DELETE SET NULL,
    budget_category_id BIGINT REFERENCES budget_categories(id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    amount_rwf DECIMAL(14,2) NOT NULL,
    paid_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    date_spent DATE NOT NULL,
    visibility_scope VARCHAR(30) NOT NULL DEFAULT 'SHARED',
    receipt_notes TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chk_expense_positive CHECK (amount_rwf > 0)
);

CREATE INDEX idx_expenses_wedding_scope ON expenses(wedding_id, visibility_scope);
CREATE INDEX idx_expenses_deleted ON expenses(deleted_at);

-- 11. CONTRIBUTIONS TABLE (Mobile Money Direct Payments)
CREATE TABLE contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    contributor_name VARCHAR(120) NOT NULL,
    contributor_phone VARCHAR(30) NOT NULL,
    amount_rwf DECIMAL(14,2) NOT NULL,
    momo_transaction_id VARCHAR(100) UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, COMPLETED, FAILED
    payment_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_contribution_positive CHECK (amount_rwf > 0)
);

CREATE INDEX idx_contributions_wedding ON contributions(wedding_id);

-- 12. GUESTS TABLE
CREATE TABLE guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(150),
    side VARCHAR(30) NOT NULL DEFAULT 'SHARED', -- BRIDE_SIDE, GROOM_SIDE, SHARED
    category VARCHAR(40) NOT NULL DEFAULT 'FRIEND', -- VIP, FAMILY, FRIEND
    plus_one_allowed INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, CONFIRMED, DECLINED
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_guests_wedding_side ON guests(wedding_id, side);

-- 13. INVITATIONS TABLE (36-char UUID Token)
CREATE TABLE invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    guest_id BIGINT NOT NULL UNIQUE REFERENCES guests(id) ON DELETE CASCADE,
    token VARCHAR(36) NOT NULL UNIQUE,
    title VARCHAR(150),
    personal_message TEXT,
    shareable_url VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_invitations_token ON invitations(token);

-- 14. RSVPS TABLE
CREATE TABLE rsvps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id BIGINT NOT NULL UNIQUE REFERENCES invitations(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL, -- ATTENDING, DECLINED, PENDING
    plus_one_names TEXT,        -- Comma separated names of attending plus-ones
    dietary_preferences TEXT,
    responded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 15. SEATING TABLES TABLE
CREATE TABLE seating_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    ceremony_id BIGINT REFERENCES wedding_ceremonies(id) ON DELETE CASCADE,
    table_name VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 8,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_seating_ceremony ON seating_tables(ceremony_id);

-- 16. GUEST SEATINGS TABLE
CREATE TABLE guest_seatings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL REFERENCES seating_tables(id) ON DELETE CASCADE,
    guest_id BIGINT NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_guest_table UNIQUE (guest_id)
);

-- 17. VENDORS TABLE
CREATE TABLE vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL, -- VENUE, CATERING, DECORATION, PHOTOGRAPHY, BEAUTY, TRANSPORT
    contact_phone VARCHAR(30),
    contact_email VARCHAR(150),
    cost_rwf DECIMAL(14,2) DEFAULT 0.00,
    booking_status VARCHAR(40) NOT NULL DEFAULT 'INQUIRY',
    payment_status VARCHAR(40) NOT NULL DEFAULT 'UNPAID',
    notes TEXT,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_vendors_wedding ON vendors(wedding_id);

-- 18. TIMELINE ITEMS TABLE
CREATE TABLE timeline_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id BIGINT NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    ceremony_id BIGINT REFERENCES wedding_ceremonies(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    target_date DATE NOT NULL,
    target_time TIME WITHOUT TIME ZONE,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_timeline_wedding ON timeline_items(wedding_id, target_date);

-- 19. PLANNING TEMPLATES TABLE
CREATE TABLE planning_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL, -- WEDDING_TASK, HOME_PREP
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 20. TEMPLATE ITEMS TABLE
CREATE TABLE template_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES planning_templates(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    item_type VARCHAR(50) NOT NULL,
    default_side VARCHAR(30) NOT NULL DEFAULT 'SHARED',
    estimated_budget DECIMAL(14,2) DEFAULT 0.00
);
