services:
  # PostgreSQL Database Service
  wedplan_db:
    image: postgres:16-alpine
    container_name: wedplan_db
    restart: always
    environment:
      POSTGRES_DB: wedplandb
      POSTGRES_USER: wedplan_user
      POSTGRES_PASSWORD: wedplan_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wedplan_user -d wedplandb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB NoSQL Database Service (Audit & Activity Logs)
  wedplan_mongo:
    image: mongo:7-jammy
    container_name: wedplan_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis NoSQL Key-Value Cache & Rate Limiter Service
  wedplan_redis:
    image: redis:7-alpine
    container_name: wedplan_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # RabbitMQ Message Broker Service
  wedplan_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: wedplan_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: wedplan_guest
      RABBITMQ_DEFAULT_PASS: wedplan_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # WedPlan Spring Boot Application Service (Backend)
  wedplan_app:
    build:
      context: ./weddingPlanner-backend
      dockerfile: Dockerfile
    container_name: wedplan_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wedplan_db:5432/wedplandb
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: wedplan_user
      SPRING_DATASOURCE_PASSWORD: wedplan_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATA_MONGODB_URI: mongodb://wedplan_mongo:27017/wedplan_logs
      SPRING_REDIS_HOST: wedplan_redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: wedplan_rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: wedplan_guest
      SPRING_RABBITMQ_PASSWORD: wedplan_password
    depends_on:
      wedplan_db:
        condition: service_healthy
      - wedplan_mongo
      - wedplan_redis
      - wedplan_rabbitmq

  # WedPlan Frontend Service (Nginx + Vite/React)
  wedplan_frontend:
    build:
      context: ./WeddingPlanner-frontend
      dockerfile: Dockerfile
    container_name: wedplan_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - wedplan_app

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
